Comment out computation of principal stresses since it breaks CBC.Swing. When enabled, I get the following error message:
 File "/scratch/src/cbc.solve/cbc/twist/problem_definitions.py", line 198, in _create_solver
    self.solver = CG1MomentumBalanceSolver(self, self.parameters["solver_parameters"])
  File "/scratch/src/cbc.solve/cbc/twist/solution_algorithms.py", line 489, in __init__
    P = problem.first_pk_stress(u_mid)
  File "/scratch/src/cbc.solve/cbc/twist/problem_definitions.py", line 63, in first_pk_stress
    return self.material_model().FirstPiolaKirchhoffStress(u)
  File "/scratch/src/cbc.solve/cbc/twist/material_model_base.py", line 92, in FirstPiolaKirchhoffStress
    S = self.SecondPiolaKirchhoffStress(u)
  File "/scratch/src/cbc.solve/cbc/twist/material_model_base.py", line 60, in SecondPiolaKirchhoffStres\
s
    self._construct_local_kinematics(u)
  File "/scratch/src/cbc.solve/cbc/twist/material_model_base.py", line 54, in _construct_local_kinemati\
cs
    [self.l1, self.l2, self.l3] = PrincipalStretches(u)
  File "/scratch/src/cbc.solve/cbc/twist/kinematics.py", line 88, in PrincipalStretches
    S = FunctionSpace(u.function_space().mesh(), "CG", 1)
AttributeError: 'ComponentTensor' object has no attribute 'function_space'